services:
  # mongodbsingle:
  #   image: "mongo:latest"
  #   container_name: mongodbsingle
  #   restart: always
  #   ports:
  #     - "27001:27017"
  #   volumes:
  #     - mongodb_data_container:/data/db
  #   networks:
  #     - appnetwork

  app-order:
    container_name: app-order
    image: juanpapiro/orderparkingbr:latest
    # depends_on:
    #   - mongodbsingle
    environment:
      - spring.data.mongodb.uri=mongodb://host.docker.internal:12001/parking
      - URL_PARKINGMETER=http://host.docker.internal:8001/parkingmeter
    ports:
      - "8003:8002"
    networks:
      - appnetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"




networks:
  appnetwork:
    name: parkingnetwork
    driver: bridge
    external: true





# volumes:
#  mongodb_data_container: